language: java
jdk:
  - oraclejdk11
  - openjdk11

services:
  - docker

branches:
  only:
    - master
    - develop

addons:
  sonarcloud:
    organization: "bananayong-github"

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - ./mvnw -PIT verify -B
  - ./mvnw sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
