version: '3.7'
services:
  mysql:
    image: 'mysql:8'
    ports:
      - '13306:3306'
    environment:
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'

  redis:
    image: 'redis'
    ports:
      - '16379:6379'